SELECT * FROM sticker;

INSERT INTO sticker (sticker_size, sticker_color) VALUES
('very small', 'red'),
('small', 'blue'),
('medium', 'green'),
('big', 'yellow'),
('very big', 'purple'),
('small', 'black'),
('medium', 'white'),
('big', 'orange'),
('very big', 'pink'),
('very small', 'gray'),
('small', 'brown'),
('medium', 'cyan'),
('big', 'violet'),
('very big', 'lime'),
('small', 'beige'),
('medium', 'magenta'),
('big', 'turquoise'),
('very big', 'indigo'),
('very small', 'teal'),
('small', 'gold');

INSERT INTO sticker (sticker_size, sticker_color) VALUES
('very small', 'silver'),
('small', 'magenta'),
('medium', 'chartreuse'),
('big', 'coral'),
('very big', 'fuchsia'),
('small', 'lavender'),
('medium', 'beige'),
('big', 'peach'),
('very big', 'mint'),
('very small', 'azure'),
('small', 'olive'),
('medium', 'salmon'),
('big', 'crimson'),
('very big', 'emerald'),
('small', 'plum'),
('medium', 'pearl'),
('big', 'amber'),
('very big', 'sapphire'),
('very small', 'amber'),
('small', 'mint'),
('medium', 'orchid'),
('big', 'periwinkle'),
('very big', 'turquoise'),
('small', 'ruby'),
('medium', 'blush'),
('big', 'emerald'),
('very big', 'scarlet'),
('small', 'teal'),
('medium', 'cobalt'),
('big', 'bronze'),
('very big', 'jade');
